# Generated by Django 3.0.7 on 2021-05-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='IC',
            field=models.CharField(default=123456789, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
