# Generated by Django 3.0.7 on 2021-09-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress_reciver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
