# Generated by Django 3.0.7 on 2021-06-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymnet_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Unconfirmend', 'Unconfirmend'), ('Recived', 'Recived')], default='Unpaid', max_length=120)),
                ('payment_slip', models.ImageField(blank=True, null=True, upload_to='orders/paymentSlips')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_slip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_slip_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymnet_status',
        ),
    ]
