# Generated by Django 3.0.7 on 2021-06-24 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
