# Generated by Django 3.0.7 on 2021-06-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210625_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_total',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Pending', 'Pending Payment Confirmation'), ('shipping', 'shipping'), ('shipped', 'shipped')], default='Unpaid', max_length=120),
        ),
    ]
