# Generated by Django 3.0.7 on 2021-09-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210626_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymnet_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Unconfirmend', 'pending payment confirmation'), ('Recived', 'Payment Received')], default='Unpaid', max_length=120),
        ),
    ]
