# Generated by Django 3.0.7 on 2021-06-22 08:30

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='key',
            field=models.CharField(default=products.models.key_genrator, max_length=15),
        ),
    ]
